// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAp--kz9oreMesiGzAxBw6QP8P-ikNWW4Y',
    appId: '1:689140004802:web:d6843e694742da9900085b',
    messagingSenderId: '689140004802',
    projectId: 'mkanak-9a474',
    authDomain: 'mkanak-9a474.firebaseapp.com',
    storageBucket: 'mkanak-9a474.firebasestorage.app',
    measurementId: 'G-2LNKL1Y30C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnPjhSgpYzcEiJfB3XZ0RaHCvvQkU3zSk',
    appId: '1:689140004802:android:bfcf45ca935da90500085b',
    messagingSenderId: '689140004802',
    projectId: 'mkanak-9a474',
    storageBucket: 'mkanak-9a474.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAc7BSrBeYkhD8OY1MgPpQJ-io9qmR-15U',
    appId: '1:689140004802:ios:1d99003c94615cd600085b',
    messagingSenderId: '689140004802',
    projectId: 'mkanak-9a474',
    storageBucket: 'mkanak-9a474.firebasestorage.app',
    iosBundleId: 'com.example.mkanak',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAc7BSrBeYkhD8OY1MgPpQJ-io9qmR-15U',
    appId: '1:689140004802:ios:1d99003c94615cd600085b',
    messagingSenderId: '689140004802',
    projectId: 'mkanak-9a474',
    storageBucket: 'mkanak-9a474.firebasestorage.app',
    iosBundleId: 'com.example.mkanak',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAp--kz9oreMesiGzAxBw6QP8P-ikNWW4Y',
    appId: '1:689140004802:web:f7db3e371fd3c82700085b',
    messagingSenderId: '689140004802',
    projectId: 'mkanak-9a474',
    authDomain: 'mkanak-9a474.firebaseapp.com',
    storageBucket: 'mkanak-9a474.firebasestorage.app',
    measurementId: 'G-1189MZPCCC',
  );
}
