// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdLuLXLDYEXxkV4vUSHdg-CFmKLAtUq64',
    appId: '1:893333876285:web:e1e9832d1a0580a8210454',
    messagingSenderId: '893333876285',
    projectId: 'mkanak-39a56',
    authDomain: 'mkanak-39a56.firebaseapp.com',
    storageBucket: 'mkanak-39a56.firebasestorage.app',
    measurementId: 'G-BED1ENW23S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWt8frWhA3QEbzbJivGMth1hcX7NxKm30',
    appId: '1:893333876285:android:4d374658fc8324dd210454',
    messagingSenderId: '893333876285',
    projectId: 'mkanak-39a56',
    storageBucket: 'mkanak-39a56.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-jYrljxIxNHv39NbFZLXnhY_qCM8ehyY',
    appId: '1:893333876285:ios:f8bc6c2743aa8289210454',
    messagingSenderId: '893333876285',
    projectId: 'mkanak-39a56',
    storageBucket: 'mkanak-39a56.firebasestorage.app',
    iosBundleId: 'com.example.mkanak',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-jYrljxIxNHv39NbFZLXnhY_qCM8ehyY',
    appId: '1:893333876285:ios:f8bc6c2743aa8289210454',
    messagingSenderId: '893333876285',
    projectId: 'mkanak-39a56',
    storageBucket: 'mkanak-39a56.firebasestorage.app',
    iosBundleId: 'com.example.mkanak',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdLuLXLDYEXxkV4vUSHdg-CFmKLAtUq64',
    appId: '1:893333876285:web:ebd0dfafa97b8796210454',
    messagingSenderId: '893333876285',
    projectId: 'mkanak-39a56',
    authDomain: 'mkanak-39a56.firebaseapp.com',
    storageBucket: 'mkanak-39a56.firebasestorage.app',
    measurementId: 'G-3Z8JD83N8S',
  );

}